### PR TITLE
Change 🍨  to 🍿 in list explanation paragraph

### LINKED ISSUE #65: Change 🍨 to 🍿 in list explanation paragraph
A paragraph in compile-and-run.md still refers to 🍨 as the beginning of a list

### PR DESCRIPTION
**Pull request by quentin-dev**
Fixes #65 

I've tried out some code examples and they only seem to work when 🍿 is changed to 🍨 as is specified in the text `Everything that you list between 🍨 and 🍆 is made into a list`

### CODE REVIEW

**Comment by thbwd** [comment]
This is 1.0 beta 2 syntax. You're probably using some older version of Emojicode.

**Comment by quentin-dev** [comment]
Closes #65

**Comment by quentin-dev** [comment]
Oh then the paragraph should be changed as it still refers to 🍨

**Comment by thbwd** [comment]
Oh, true, looks like I didn’t catch that when updating the guide.

**Comment by quentin-dev** [comment]
I'm on it, I'll update this MR and the corresponding issue

**Comment by quentin-dev** [comment]
Should be good @thbwd !

**Comment by thbwd** [comment]
Great, thanks!

**Pull request merged**
